# Copyright 2017-2020 Orbital Insight Inc., all rights reserved.
# Contains confidential and trade secret information.
# Government Users:  Commercial Computer Software - Use governed by
# terms of Orbital Insight commercial license agreement.

package:
  name: datasets
  version: "{{ version }}"

source:
  path: ../../


build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt


requirements:
  build:
    - setuptools
    - pyyaml
    - python {{ python }}
  run:
    - scikit-learn

about:
  home: https://github.com/vikash-oi/test
  summary: 'sklearn test'
